# coding: utf-8
# 计算机网络（NET）段 —— 自 seed_data.py 第 5-590 行二进制原样搬运（M-4 ③）。
# 含：SEED_KNOWLEDGE_CHUNKS / SEED_QUESTIONS / SEED_SUBJECTS /
#      KNOWLEDGE_GRAPH / LEARNING_PATH_DAG（NET 基础图，派生阶段被当作 NET 源使用）
# 另有 CO_SEED_KNOWLEDGE_CHUNKS / OS_SEED_KNOWLEDGE_CHUNKS 的**第一版**残留定义
#    （原文第 390 / 425 行），会被 seed/co.py、seed/os.py 的同名定义覆盖 —— 别删，
#     求值顺序保真是这次拆分的硬要求。
SEED_KNOWLEDGE_CHUNKS = [
    # ---- 第1章 计算机网络概述 ----
    {"content": "计算机网络是互连的、自治的计算机集合。由资源子网和通信子网组成，核心功能是数据通信和资源共享。", "metadata": {"subject": "overview", "chapter": "概述", "type": "knowledge_point"}},
    {"content": "OSI七层模型：物理层→数据链路层→网络层→运输层→会话层→表示层→应用层。TCP/IP四层模型：网络接口层→网际层→运输层→应用层。", "metadata": {"subject": "overview", "chapter": "体系结构", "type": "knowledge_point"}},
    {"content": "分组交换采用存储转发机制，数据被分割成数据包（分组），每个分组独立选择路由，动态分配传输带宽，利用率高。", "metadata": {"subject": "overview", "chapter": "分组交换", "type": "knowledge_point"}},
    # ---- 第2章 物理层 ----
    {"content": "物理层的主要任务：确定与传输媒体的接口特性（机械特性、电气特性、功能特性、过程特性），实现比特流的传输。", "metadata": {"subject": "physical", "chapter": "基本概念", "type": "knowledge_point"}},
    {"content": "信道复用技术：频分复用FDM、时分复用TDM、波分复用WDM、码分复用CDM。其中CDMA是码分多址的简称。", "metadata": {"subject": "physical", "chapter": "信道复用", "type": "knowledge_point"}},
    {"content": "常用的传输媒体包括双绞线（最大100m）、同轴电缆、光纤（单模/多模）、无线传输（无线电波/微波/红外）。", "metadata": {"subject": "physical", "chapter": "传输媒体", "type": "knowledge_point"}},
    # ---- 第3章 数据链路层 ----
    {"content": "数据链路层使用MAC地址（48位，前24位为OUI厂商代码）。封装成帧、透明传输、差错检测是链路层的三个基本问题。", "metadata": {"subject": "datalink", "chapter": "基本概念", "type": "knowledge_point"}},
    {"content": "CSMA/CD协议：先听后发、边听边发、冲突停发、随机重发。截断二进制指数退避算法：退避时间=2^k×基本退避时间，k=min(重传次数,10)。", "metadata": {"subject": "datalink", "chapter": "CSMA/CD", "type": "knowledge_point"}},
    {"content": "以太网交换机工作在数据链路层，根据MAC地址转发。VLAN通过802.1Q标记实现虚拟局域网隔离，最大4096个VLAN。", "metadata": {"subject": "datalink", "chapter": "交换机与VLAN", "type": "knowledge_point"}},
    # ---- 第4章 网络层 ----
    {"content": "IP地址是32位二进制数（IPv4），通常用点分十进制表示。A类(0-127)、B类(128-191)、C类(192-223)是主分类。", "metadata": {"subject": "network", "chapter": "IP地址", "type": "knowledge_point"}},
    {"content": "子网划分：将IP地址的主机号部分借位作为子网号。子网掩码中1对应网络号+子网号，0对应主机号。CIDR无分类域间路由使用/前缀长度表示。", "metadata": {"subject": "network", "chapter": "子网划分", "type": "knowledge_point"}},
    {"content": "ARP协议（地址解析协议）：将IP地址解析为MAC地址，用于同一局域网内寻址。主机广播ARP请求（含目标IP），目标主机单播ARP响应（含自身MAC），请求方将IP-MAC映射写入ARP缓存（生存期通常20分钟）。", "metadata": {"subject": "network", "chapter": "ARP", "type": "knowledge_point"}},
    {"content": "路由选择协议：RIP（距离向量，跳数≤15，30s更新）、OSPF（链路状态，Dijkstra算法，区域划分）、BGP（路径向量，策略路由）。", "metadata": {"subject": "network", "chapter": "路由协议", "type": "knowledge_point"}},
    {"content": "IP协议（网际协议）提供无连接、不可靠的网络层服务：不建立连接、不保证交付、不保证顺序、无差错恢复（尽力交付）。IPv4首部固定部分20字节（含可选字段总长20~60字节），含版本、首部长度、总长度、标识/标志/片偏移、TTL、协议、首部校验和、源/目的IP地址。", "metadata": {"subject": "network", "chapter": "IP服务", "type": "knowledge_point"}},
    {"content": "路由器按路由表转发分组：提取分组目的IP地址，查路由表匹配表项，选出对应下一跳(nexthop)与出接口。匹配采用最长前缀匹配(LPM)：目的IP与表项目的网络前缀按位与，选取子网掩码最长（最具体）的匹配项；缺省路由(0.0.0.0/0)作最后兜底。", "metadata": {"subject": "network", "chapter": "路由转发", "type": "knowledge_point"}},
    # ---- 第5章 运输层 ----
    {"content": "TCP是面向连接的可靠传输协议，提供全双工通信。UDP是无连接的不可靠传输协议，开销小，适合实时应用。", "metadata": {"subject": "transport", "chapter": "概述", "type": "knowledge_point"}},
    {"content": "TCP三次握手：①客户端→SYN(seq=x)→服务器 ②服务器→SYN+ACK(seq=y,ack=x+1)→客户端 ③客户端→ACK(seq=x+1,ack=y+1)→服务器。", "metadata": {"subject": "transport", "chapter": "TCP", "type": "knowledge_point"}},
    {"content": "TCP拥塞控制四种算法：慢启动（指数增长）、拥塞避免（线性增长/加法增大）、快重传（收到3个冗余ACK立即重传）、快恢复（减半阈值后进入拥塞避免）。", "metadata": {"subject": "transport", "chapter": "拥塞控制", "type": "knowledge_point"}},
    {"content": "TCP可靠传输四大机制：(1)序号与确认——发送方为每个字节编号，接收方用累计确认(ACK)告知期望接收的下一字节序号；(2)重传——超时重传+快速重传(收到3个重复ACK立即重传)；(3)滑动窗口——接收方通告窗口大小实现流量控制，发送方在窗口内连续发送无需逐包等待；(4)拥塞控制——慢启动/拥塞避免/快重传/快恢复防止网络过载。", "metadata": {"subject": "transport", "chapter": "可靠传输", "type": "knowledge_point"}},
    # ---- 第6章 应用层 ----
    {"content": "DNS域名解析：递归查询和迭代查询两种方式。顶级域名包括.com/.org/.cn等，二级域名如baidu.com。", "metadata": {"subject": "application", "chapter": "DNS", "type": "knowledge_point"}},
    {"content": "HTTP是超文本传输协议（80端口），无状态、无连接。HTTPS=HTTP+SSL/TLS（443端口），提供加密传输和身份认证。", "metadata": {"subject": "application", "chapter": "HTTP/HTTPS", "type": "knowledge_point"}},
    {"content": "HTTP本身是无状态协议（每次请求独立、服务器不保留前次状态）。维持会话状态常用：Cookie（服务器经Set-Cookie下发，浏览器后续请求自动携带、存于客户端）、Session（服务端保存会话状态、客户端仅持会话ID存于Cookie）、Token（如JWT无状态令牌携鉴权信息）。", "metadata": {"subject": "application", "chapter": "HTTP会话", "type": "knowledge_point"}},
    {"content": "FTP（文件传输协议，20/21端口）采用客户端/服务器模式，基于TCP。控制连接(21)和数据连接(20)分开。", "metadata": {"subject": "application", "chapter": "FTP", "type": "knowledge_point"}},
    {"content": "HTTP请求方法：GET（获取资源）、POST（提交数据）、PUT（更新资源）、DELETE（删除资源）、HEAD（获取首部）。状态码：1xx信息、2xx成功(200 OK)、3xx重定向(301永久/302临时)、4xx客户端错误(404 Not Found)、5xx服务器错误(500)。", "metadata": {"subject": "application", "chapter": "HTTP", "type": "knowledge_point"}},
    {"content": "HTTP首部字段：通用首部(Cache-Control/Connection)、请求首部(Host/User-Agent/Accept)、响应首部(Server/WWW-Authenticate)、实体首部(Content-Type/Content-Length/Content-Encoding)。", "metadata": {"subject": "application", "chapter": "HTTP", "type": "knowledge_point"}},
    {"content": "HTTP/2特性：二进制分帧、多路复用(一个TCP连接并行多个请求)、头部压缩(HPACK)、服务器推送。HTTP/3基于QUIC(UDP)，解决TCP队头阻塞问题。", "metadata": {"subject": "application", "chapter": "HTTP", "type": "knowledge_point"}},
    {"content": "DNS解析全过程：浏览器缓存→系统缓存→hosts文件→本地DNS服务器(递归)→根域名服务器→顶级域名服务器→权威域名服务器(迭代)→返回IP。默认端口53，基于UDP。", "metadata": {"subject": "application", "chapter": "DNS", "type": "knowledge_point"}},
    {"content": "DNS记录类型：A(IPv4地址)、AAAA(IPv6地址)、CNAME(别名)、MX(邮件交换)、NS(域名服务器)、TXT(文本记录)、PTR(反向解析)。TTL控制缓存生存时间。", "metadata": {"subject": "application", "chapter": "DNS", "type": "knowledge_point"}},
    {"content": "电子邮件系统三大组件：用户代理(UA)、邮件服务器、SMTP。发送用SMTP(25端口)，接收用POP3(110)或IMAP(143)。MIME扩展支持多媒体附件。", "metadata": {"subject": "application", "chapter": "电子邮件", "type": "knowledge_point"}},
    {"content": "DHCP动态主机配置协议(67/68端口，基于UDP)自动分配IP地址：DISCOVER→OFFER→REQUEST→ACK四步。租约期到了需续租(RENEW/REBIND)。", "metadata": {"subject": "application", "chapter": "DHCP", "type": "knowledge_point"}},
    {"content": "WWW万维网由URL(统一资源定位符)、HTTP(传输协议)、HTML(超文本标记语言)三部分组成。URL格式：协议://主机:端口/路径?查询#片段。", "metadata": {"subject": "application", "chapter": "WWW", "type": "knowledge_point"}},
    {"content": "P2P应用：BitTorrent(文件共享)、Skype(VoIP)。与C/S模式对比：P2P每个节点既是客户端又是服务器，扩展性好，但管理困难。CDN内容分发网络缓存就近服务。", "metadata": {"subject": "application", "chapter": "P2P/CDN", "type": "knowledge_point"}},
    # ---- 第7章 网络安全 ----
    {"content": "SSL/TLS协议在传输层之上提供安全服务：握手协议（身份认证+密钥协商）、记录协议（数据加密+完整性校验）。HTTPS由此提供四大保证：机密性（对称加密防窃听）、完整性（MAC/哈希防篡改）、身份认证（证书+非对称加密验证对方身份）、不可否认性；对称密钥用于加密数据、非对称加密用于协商对称会话密钥。", "metadata": {"subject": "security", "chapter": "SSL/TLS", "type": "knowledge_point"}},
    {"content": "防火墙是位于网络边界的安全设备，通过规则集控制进出网络的流量。常见类型：包过滤防火墙、状态检测防火墙、应用代理防火墙。", "metadata": {"subject": "security", "chapter": "防火墙", "type": "knowledge_point"}},
    {"content": "常见的网络攻击类型：DDoS（分布式拒绝服务攻击）、SQL注入、XSS跨站脚本、中间人攻击MITM、ARP欺骗、DNS劫持。", "metadata": {"subject": "security", "chapter": "网络攻击", "type": "knowledge_point"}},
    {"content": "密码学两大类：对称加密(加密解密同一密钥，DES/AES/3DES，速度快适合大批量)、非对称加密(公钥加密私钥解密，RSA/ECC，安全但慢)。混合加密：用非对称交换对称密钥，再用对称加密数据。", "metadata": {"subject": "security", "chapter": "密码学", "type": "knowledge_point"}},
    {"content": "AES对称加密：分组长度128位，密钥长度128/192/256位，轮数10/12/14。取代DES(56位密钥已被暴力破解)。AES的SubBytes/ShiftRows/MixColumns/AddRoundKey四步轮变换。", "metadata": {"subject": "security", "chapter": "密码学", "type": "knowledge_point"}},
    {"content": "RSA非对称加密：基于大整数分解难题。密钥生成：选两素数p,q→n=pq,φ(n)=(p-1)(q-1)→选e→算d。公钥(n,e)，私钥(n,d)。加密c=m^e mod n，解密m=c^d mod n。", "metadata": {"subject": "security", "chapter": "密码学", "type": "knowledge_point"}},
    {"content": "报文摘要(哈希)：MD5(128位，已不安全)、SHA-1(160位，已弃用)、SHA-256(256位，推荐)。特性：固定长度输出、单向不可逆、抗碰撞。用于完整性校验和数字签名。", "metadata": {"subject": "security", "chapter": "报文摘要", "type": "knowledge_point"}},
    {"content": "数字签名：发送方用私钥对消息摘要加密，接收方用公钥验证。提供身份认证、完整性、不可否认性。签名=加密(哈希(消息),发送方私钥)。", "metadata": {"subject": "security", "chapter": "数字签名", "type": "knowledge_point"}},
    {"content": "数字证书：CA(证书颁发机构)用其私钥对(公钥+持有者身份+有效期)签名。证书链：根CA→中间CA→终端证书。浏览器信任根CA预置公钥，逐级验证签名。X.509标准。", "metadata": {"subject": "security", "chapter": "数字证书", "type": "knowledge_point"}},
    {"content": "TLS 1.3握手(1-RTT)：ClientHello(含支持的密码套件+key_share)→ServerHello(选定套件+key_share)→双方算出共享密钥→加密传输。相比TLS 1.2简化握手，废弃RSA密钥交换，强制前向安全。", "metadata": {"subject": "security", "chapter": "SSL/TLS", "type": "knowledge_point"}},
    {"content": "HTTPS证书验证流程：服务器返回证书链→浏览器验证证书签名(用CA公钥)→检查有效期/域名匹配/吊销列表(CRL/OCSP)→通过后用证书公钥加密预主密钥交换。", "metadata": {"subject": "security", "chapter": "SSL/TLS", "type": "knowledge_point"}},
    {"content": "DDoS攻击分类：流量型(SYN Flood/UDP Flood/ICMP Flood，耗尽带宽)、协议型(慢速攻击，耗尽连接)、应用层型(HTTP Flood/CC，伪装正常请求)。防御：流量清洗、CDN分散、限流。", "metadata": {"subject": "security", "chapter": "DDoS", "type": "knowledge_point"}},
    {"content": "SYN Flood攻击：攻击者发送大量伪造源IP的SYN包，服务器为每个分配资源并回复SYN+ACK等待ACK，半连接队列填满导致正常用户无法连接。防御：SYN Cookie(不分配资源直至ACK到达)、增大队列、防火墙过滤。", "metadata": {"subject": "security", "chapter": "DDoS", "type": "knowledge_point"}},
    {"content": "SQL注入：攻击者在输入中嵌入SQL片段，篡改查询逻辑。防御：参数化查询(预编译语句)、输入过滤、最小权限原则、WAF。分类：布尔盲注、时间盲注、联合查询、堆叠查询。", "metadata": {"subject": "security", "chapter": "Web攻击", "type": "knowledge_point"}},
    {"content": "XSS跨站脚本：攻击者注入恶意脚本到网页，受害者浏览器执行。分类：存储型(存数据库)、反射型(URL参数)、DOM型。窃取Cookie/会话劫持。防御：输出编码、CSP策略、HttpOnly Cookie。", "metadata": {"subject": "security", "chapter": "Web攻击", "type": "knowledge_point"}},
    {"content": "ARP欺骗：攻击者伪造ARP响应，将自己MAC与网关IP绑定，流量被中间人截获。防御：静态ARP绑定、DAI(动态ARP检测)、端口隔离。DNS劫持类似，伪造DNS响应。", "metadata": {"subject": "security", "chapter": "网络攻击", "type": "knowledge_point"}},
    {"content": "中间人攻击MITM：攻击者拦截并可能篡改双方通信。HTTPS通过证书体系防御，但用户忽略证书警告仍可被攻破。WiFi环境下伪造AP是常见MITM手段。", "metadata": {"subject": "security", "chapter": "网络攻击", "type": "knowledge_point"}},
    {"content": "IDS入侵检测系统：旁路部署，监测并报警。IPS入侵防御系统：串联部署，可阻断。检测方式：特征库匹配(已知攻击)、异常检测(偏离基线)。Snort/Suricata是开源IDS。", "metadata": {"subject": "security", "chapter": "IDS/IPS", "type": "knowledge_point"}},
    {"content": "VPN虚拟专用网：在公共网络上建立加密隧道。IPSec工作在网络层(AH认证/ESP加密/IKE密钥协商)，SSL VPN工作在应用层(浏览器即可)。保证机密性、完整性、身份认证。", "metadata": {"subject": "security", "chapter": "VPN", "type": "knowledge_point"}},
    {"content": "网络安全五要素：机密性(加密)、完整性(哈希/MAC)、可用性(抗DDoS)、可控性(访问控制)、不可否认性(数字签名)。CIA三要素为核心。", "metadata": {"subject": "security", "chapter": "安全基础", "type": "knowledge_point"}},
]

SEED_QUESTIONS = [
    # 计算机网络概述
    {"id": "q1", "subject": "overview", "chapter": "概述", "type": "choice", "difficulty": "easy",
     "text": "计算机网络最基本的功能是？",
     "options": ["数据通信和资源共享", "分布式处理", "负载均衡", "数据加密"], "answer": 0, "source": "计算机网络教程 第1章"},
    {"id": "q2", "subject": "overview", "chapter": "体系结构", "type": "choice", "difficulty": "medium",
     "text": "OSI参考模型从下到上的第三层是？",
     "options": ["数据链路层", "传输层", "网络层", "会话层"], "answer": 2, "source": "计算机网络教程 第1章"},
    # 数据链路层
    {"id": "q3", "subject": "datalink", "chapter": "CSMA/CD", "type": "choice", "difficulty": "medium",
     "text": "在CSMA/CD中，站点检测到冲突后，退避时间取决于？",
     "options": ["随机数", "重传次数", "帧长度", "传输速率"], "answer": 1, "source": "计算机网络教程 第3章"},
    {"id": "q4", "subject": "datalink", "chapter": "差错检测", "type": "fill", "difficulty": "hard",
     "text": "CRC校验中，若生成多项式为G(x)=x³+x+1，则其对应的二进制除数是______",
     "answer": "1011", "source": "计算机网络教程 第3章"},
    # 网络层
    {"id": "q5", "subject": "network", "chapter": "IP地址", "type": "choice", "difficulty": "medium",
     "text": "IP地址 192.168.1.0/24 可以分配多少个可用主机地址？",
     "options": ["254", "255", "256", "252"], "answer": 0, "source": "计算机网络教程 第4章"},
    {"id": "q6", "subject": "network", "chapter": "子网划分", "type": "compute", "difficulty": "hard",
     "text": "将 192.168.1.0/24 划分为4个等长子网，写出每个子网的网络地址、广播地址和可用主机范围。",
     "answer": "子网1: 192.168.1.0/26, 广播 192.168.1.63, 可用 1-62", "source": "计算机网络教程 第4章"},
    # 运输层
    {"id": "q7", "subject": "transport", "chapter": "TCP", "type": "choice", "difficulty": "easy",
     "text": "TCP三次握手中，客户端发送的第一个报文段的标志位是？",
     "options": ["ACK", "SYN", "SYN+ACK", "FIN"], "answer": 1, "source": "计算机网络教程 第5章"},
    {"id": "q8", "subject": "transport", "chapter": "拥塞控制", "type": "choice", "difficulty": "medium",
     "text": "TCP拥塞控制中，慢启动阶段的窗口增长方式是？",
     "options": ["线性增长", "指数增长", "对数增长", "固定值"], "answer": 1, "source": "计算机网络教程 第5章"},
    # 应用层
    {"id": "q9", "subject": "application", "chapter": "HTTP", "type": "choice", "difficulty": "easy",
     "text": "HTTP默认使用哪个端口？",
     "options": ["80", "443", "8080", "21"], "answer": 0, "source": "计算机网络教程 第6章"},
    {"id": "q10", "subject": "application", "chapter": "DNS", "type": "choice", "difficulty": "medium",
     "text": "DNS域名解析中，迭代查询的特点是？",
     "options": ["服务器直接返回结果", "服务器告知下一站地址由客户端自行查询", "服务器代替客户端继续查询", "使用广播查询"], "answer": 1, "source": "计算机网络教程 第6章"},
    # 网络安全
    {"id": "q11", "subject": "security", "chapter": "TLS", "type": "choice", "difficulty": "medium",
     "text": "HTTPS使用的安全协议栈是在HTTP下增加了哪一层？",
     "options": ["IPsec", "SSL/TLS", "SSH", "PGP"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q12", "subject": "security", "chapter": "防火墙", "type": "choice", "difficulty": "easy",
     "text": "包过滤防火墙主要依据什么进行过滤？",
     "options": ["MAC地址", "IP地址和端口号", "应用层协议", "用户名"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q13", "subject": "network", "chapter": "IP地址", "type": "compute", "difficulty": "hard",
     "text": "将 192.168.1.0/24 划分为4个等长子网，写出每个子网的网络地址和广播地址。",
     "answer": "192.168.1.0/26 ~ 192.168.1.192/26", "source": "计算机网络教程 第4章"},
    {"id": "q14", "subject": "transport", "chapter": "拥塞控制", "type": "fill", "difficulty": "medium",
     "text": "TCP拥塞控制中，拥塞避免阶段的窗口增长方式是______增长，而慢启动阶段是______增长。",
     "answer": "线性、指数", "source": "计算机网络教程 第5章"},
    # ── 应用层补充题 ──
    {"id": "q15", "subject": "application", "chapter": "HTTP", "type": "choice", "difficulty": "medium",
     "text": "HTTP状态码 301 表示？",
     "options": ["请求成功", "永久重定向", "临时重定向", "资源未找到"], "answer": 1, "source": "计算机网络教程 第6章"},
    {"id": "q16", "subject": "application", "chapter": "HTTP", "type": "choice", "difficulty": "medium",
     "text": "HTTP/2 相比 HTTP/1.1 的主要改进不包括？",
     "options": ["二进制分帧", "多路复用", "头部压缩", "基于UDP传输"], "answer": 3, "source": "计算机网络教程 第6章"},
    {"id": "q17", "subject": "application", "chapter": "DNS", "type": "choice", "difficulty": "medium",
     "text": "DNS中 MX 记录的作用是？",
     "options": ["IPv4地址", "IPv6地址", "邮件交换服务器", "别名指向"], "answer": 2, "source": "计算机网络教程 第6章"},
    {"id": "q18", "subject": "application", "chapter": "DNS", "type": "fill", "difficulty": "medium",
     "text": "DNS默认使用的端口是______，基于______协议传输。",
     "answer": "53、UDP", "source": "计算机网络教程 第6章"},
    {"id": "q19", "subject": "application", "chapter": "电子邮件", "type": "choice", "difficulty": "medium",
     "text": "用户从邮件服务器读取邮件常用的协议是？",
     "options": ["SMTP", "FTP", "POP3", "HTTP"], "answer": 2, "source": "计算机网络教程 第6章"},
    {"id": "q20", "subject": "application", "chapter": "DHCP", "type": "choice", "difficulty": "medium",
     "text": "DHCP分配IP地址的四步交互顺序是？",
     "options": ["DISCOVER→OFFER→REQUEST→ACK", "REQUEST→OFFER→DISCOVER→ACK", "DISCOVER→REQUEST→OFFER→ACK", "OFFER→DISCOVER→REQUEST→ACK"], "answer": 0, "source": "计算机网络教程 第6章"},
    {"id": "q21", "subject": "application", "chapter": "HTTP", "type": "choice", "difficulty": "easy",
     "text": "下列哪个HTTP方法用于向服务器提交数据？",
     "options": ["GET", "POST", "HEAD", "OPTIONS"], "answer": 1, "source": "计算机网络教程 第6章"},
    # ── 网络安全补充题 ──
    {"id": "q22", "subject": "security", "chapter": "密码学", "type": "choice", "difficulty": "medium",
     "text": "下列属于非对称加密算法的是？",
     "options": ["DES", "AES", "RSA", "3DES"], "answer": 2, "source": "计算机网络教程 第7章"},
    {"id": "q23", "subject": "security", "chapter": "密码学", "type": "choice", "difficulty": "medium",
     "text": "AES加密算法的分组长度是？",
     "options": ["64位", "128位", "256位", "512位"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q24", "subject": "security", "chapter": "报文摘要", "type": "choice", "difficulty": "medium",
     "text": "下列哈希算法中目前推荐使用的是？",
     "options": ["MD5", "SHA-1", "SHA-256", "CRC32"], "answer": 2, "source": "计算机网络教程 第7章"},
    {"id": "q25", "subject": "security", "chapter": "数字签名", "type": "choice", "difficulty": "medium",
     "text": "数字签名发送方使用的是？",
     "options": ["自己的公钥", "自己的私钥", "接收方的公钥", "接收方的私钥"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q26", "subject": "security", "chapter": "数字证书", "type": "choice", "difficulty": "hard",
     "text": "数字证书的签发者是？",
     "options": ["服务器自身", "用户自己", "CA证书颁发机构", "浏览器厂商"], "answer": 2, "source": "计算机网络教程 第7章"},
    {"id": "q27", "subject": "security", "chapter": "DDoS", "type": "choice", "difficulty": "medium",
     "text": "SYN Flood攻击利用的漏洞是？",
     "options": ["TCP握手时服务器分配半连接资源", "UDP无连接特性", "ICMP广播", "DNS递归查询"], "answer": 0, "source": "计算机网络教程 第7章"},
    {"id": "q28", "subject": "security", "chapter": "DDoS", "type": "choice", "difficulty": "medium",
     "text": "下列哪种技术能有效防御SYN Flood攻击？",
     "options": ["增大缓存", "SYN Cookie", "关闭防火墙", "使用UDP"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q29", "subject": "security", "chapter": "Web攻击", "type": "choice", "difficulty": "medium",
     "text": "SQL注入攻击最有效的防御手段是？",
     "options": ["输入过滤", "参数化查询", "隐藏数据库", "加密网页"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q30", "subject": "security", "chapter": "Web攻击", "type": "choice", "difficulty": "medium",
     "text": "XSS攻击中攻击者注入的代码在哪里执行？",
     "options": ["服务器端", "数据库", "受害者浏览器", "CDN节点"], "answer": 2, "source": "计算机网络教程 第7章"},
    {"id": "q31", "subject": "security", "chapter": "网络攻击", "type": "choice", "difficulty": "medium",
     "text": "ARP欺骗攻击的核心是伪造？",
     "options": ["IP地址", "MAC地址与IP的映射", "DNS响应", "TCP序列号"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q32", "subject": "security", "chapter": "IDS/IPS", "type": "choice", "difficulty": "hard",
     "text": "IDS与IPS的关键区别是？",
     "options": ["检测方式不同", "IDS旁路报警，IPS串联可阻断", "IDS用硬件，IPS用软件", "无区别"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q33", "subject": "security", "chapter": "VPN", "type": "choice", "difficulty": "medium",
     "text": "IPSec VPN工作在OSI的哪一层？",
     "options": ["数据链路层", "网络层", "运输层", "应用层"], "answer": 1, "source": "计算机网络教程 第7章"},
    {"id": "q34", "subject": "security", "chapter": "安全基础", "type": "fill", "difficulty": "medium",
     "text": "网络安全CIA三要素指机密性、______和可用性。",
     "answer": "完整性", "source": "计算机网络教程 第7章"},
    {"id": "q35", "subject": "security", "chapter": "SSL/TLS", "type": "choice", "difficulty": "hard",
     "text": "TLS 1.3 相比 TLS 1.2 的改进是？",
     "options": ["增加RSA密钥交换", "简化握手为1-RTT", "使用UDP传输", "取消证书验证"], "answer": 1, "source": "计算机网络教程 第7章"},
    # ── 扩展题（四科） ──
    {"id": "q36", "subject": "overview", "chapter": "性能指标", "type": "fill", "difficulty": "easy",
     "text": "计算机网络中，比特率的单位是______。", "answer": "bps", "source": "计算机网络教程 第1章"},
    {"id": "q37", "subject": "physical", "chapter": "信道复用", "type": "choice", "difficulty": "medium",
     "text": "下列哪种复用技术是光纤通信特有的？", "options": ["FDM", "TDM", "WDM", "CDM"], "answer": 2, "source": "计算机网络教程 第2章"},
    {"id": "q38", "subject": "datalink", "chapter": "以太网", "type": "choice", "difficulty": "medium",
     "text": "以太网MAC地址的长度是？", "options": ["32位", "48位", "64位", "128位"], "answer": 1, "source": "计算机网络教程 第3章"},
    {"id": "q39", "subject": "network", "chapter": "IP地址", "type": "choice", "difficulty": "medium",
     "text": "IPv6地址的长度是？", "options": ["32位", "64位", "128位", "256位"], "answer": 2, "source": "计算机网络教程 第4章"},
    {"id": "q40", "subject": "network", "chapter": "路由协议", "type": "choice", "difficulty": "medium",
     "text": "OSPF的Hello报文用于？", "options": ["发现和维持邻居关系", "传输路由表", "交换链路状态", "建立AS间连接"], "answer": 0, "source": "计算机网络教程 第4章"},
    {"id": "q41", "subject": "transport", "chapter": "TCP", "type": "fill", "difficulty": "medium",
     "text": "TCP段的首部最小长度是______字节。", "answer": "20", "source": "计算机网络教程 第5章"},
    {"id": "q42", "subject": "application", "chapter": "HTTP", "type": "choice", "difficulty": "easy",
     "text": "HTTP状态码404表示？", "options": ["服务器错误", "资源未找到", "请求超时", "禁止访问"], "answer": 1, "source": "计算机网络教程 第6章"},
    {"id": "q43", "subject": "security", "chapter": "防火墙", "type": "fill", "difficulty": "easy",
     "text": "防火墙的三种类型是包过滤、______和代理防火墙。", "answer": "状态检测", "source": "计算机网络教程 第7章"},
    {"id": "q44", "subject": "ds_tree", "chapter": "二叉树", "type": "choice", "difficulty": "easy",
     "text": "完全二叉树中，编号为i的节点若存在左孩子，其左孩子编号为？", "options": ["2i", "2i+1", "i/2", "i+1"], "answer": 0, "source": "数据结构 第5章"},
    {"id": "q45", "subject": "ds_stack", "chapter": "栈", "type": "fill", "difficulty": "easy",
     "text": "栈的特点是______。", "answer": "后进先出(LIFO)", "source": "数据结构 第3章"},
    {"id": "q46", "subject": "ds_sort", "chapter": "插入排序", "type": "choice", "difficulty": "easy",
     "text": "直接插入排序在最好情况下的时间复杂度是？", "options": ["O(n)", "O(n^2)", "O(nlogn)", "O(logn)"], "answer": 0, "source": "数据结构 第8章"},
    {"id": "q47", "subject": "ds_graph", "chapter": "遍历", "type": "choice", "difficulty": "medium",
     "text": "图的深度优先遍历(DFS)使用的数据结构是？", "options": ["队列", "栈", "数组", "链表"], "answer": 1, "source": "数据结构 第6章"},
    {"id": "q48", "subject": "co_data", "chapter": "定点数", "type": "fill", "difficulty": "medium",
     "text": "8位补码11111111表示的十进制值是______。", "answer": "-1", "source": "计算机组成原理 第2章"},
    {"id": "q49", "subject": "co_memory", "chapter": "Cache", "type": "choice", "difficulty": "medium",
     "text": "提高Cache命中率的方法不包括？", "options": ["增大Cache容量", "提高映射灵活性", "降低主存容量", "采用替换算法"], "answer": 2, "source": "计算机组成原理 第3章"},
    {"id": "q50", "subject": "co_io", "chapter": "DMA", "type": "fill", "difficulty": "medium",
     "text": "DMA方式的数据传送单位是______。", "answer": "数据块", "source": "计算机组成原理 第7章"},
    {"id": "q51", "subject": "os_process", "chapter": "调度算法", "type": "choice", "difficulty": "easy",
     "text": "下列调度算法中，时间片的大小直接影响系统性能的是？", "options": ["FCFS", "RR(时间片轮转)", "SJF", "优先级调度"], "answer": 1, "source": "操作系统 第2章"},
    {"id": "q52", "subject": "os_memory", "chapter": "分页", "type": "fill", "difficulty": "easy",
     "text": "在分页存储管理中，CPU产生的地址称为______地址。", "answer": "逻辑（或虚拟）", "source": "操作系统 第3章"},
    {"id": "q53", "subject": "os_file", "chapter": "磁盘调度", "type": "choice", "difficulty": "medium",
     "text": "磁盘调度中，N-Step SCAN相比SCAN的优势是？", "options": ["减少寻道时间", "防止饥饿", "提高吞吐量", "降低能耗"], "answer": 1, "source": "操作系统 第4章"},
    {"id": "q54", "subject": "ds_search", "chapter": "B树", "type": "choice", "difficulty": "hard",
     "text": "3阶B树的一个节点最多可以有多少个关键字？", "options": ["1", "2", "3", "4"], "answer": 1, "source": "数据结构 第7章"},
    {"id": "q55", "subject": "ds_sort", "chapter": "基数排序", "type": "choice", "difficulty": "medium",
     "text": "基数排序的稳定性是？", "options": ["稳定", "不稳定", "取决于基数", "取决于排序趟数"], "answer": 0, "source": "数据结构 第8章"},
    {"id": "q56", "subject": "co_cpu", "chapter": "流水线", "type": "choice", "difficulty": "hard",
     "text": "五段流水线中，EX阶段的功能是？", "options": ["取指令", "译码", "执行计算", "写回"], "answer": 2, "source": "计算机组成原理 第5章"},
    {"id": "q57", "subject": "co_memory", "chapter": "DRAM", "type": "fill", "difficulty": "medium",
     "text": "典型的DRAM刷新周期是______ms。", "answer": "64", "source": "计算机组成原理 第3章"},
    {"id": "q58", "subject": "os_overview", "chapter": "内核态", "type": "choice", "difficulty": "easy",
     "text": "用户态切换到内核态的方式是？", "options": ["系统调用", "函数调用", "程序跳转", "信号处理"], "answer": 0, "source": "操作系统 第1章"},
    {"id": "q59", "subject": "os_process", "chapter": "死锁", "type": "choice", "difficulty": "medium",
     "text": "系统有5个进程和4个同类资源，每个进程最多需要3个资源，则系统是否会死锁？", "options": ["一定死锁", "可能死锁", "一定不死锁", "无法判断"], "answer": 1, "source": "操作系统 第2章"},
    {"id": "q60", "subject": "ds_linear", "chapter": "顺序表", "type": "choice", "difficulty": "easy",
     "text": "顺序存储结构的最大缺点是？", "options": ["存储密度低", "插入删除操作效率低", "查找效率低", "只能顺序存取"], "answer": 1, "source": "数据结构 第2章"},
    {"id": "q61", "subject": "physical", "chapter": "传输媒体", "type": "fill", "difficulty": "easy",
     "text": "UTP的中文含义是______。", "answer": "非屏蔽双绞线", "source": "计算机网络教程 第2章"},
    # ── 扩展题②（四科全覆盖）──
    {"id": "q62", "subject": "overview", "chapter": "分组交换", "type": "choice", "difficulty": "medium",
     "text": "分组交换中每个分组除数据外还需包含？", "options": ["源IP", "目的地址+序号", "源MAC", "端口号"], "answer": 1, "source": "计网 第1章"},
    {"id": "q63", "subject": "network", "chapter": "NAT", "type": "choice", "difficulty": "medium",
     "text": "NAT的主要作用？", "options": ["提高网速", "解决IPv4短缺", "数据加密", "负载均衡"], "answer": 1, "source": "计网 第4章"},
    {"id": "q64", "subject": "ds_tree", "chapter": "二叉树", "type": "choice", "difficulty": "medium",
     "text": "完全二叉树1000节点，叶子节点数？", "options": ["500", "490", "501", "511"], "answer": 0, "source": "数据结构 第5章"},
    {"id": "q65", "subject": "ds_stack", "chapter": "栈", "type": "choice", "difficulty": "medium",
     "text": "后缀表达式3 4 + 5 *的值？", "options": ["35", "27", "45", "15"], "answer": 0, "source": "数据结构 第3章"},
    {"id": "q66", "subject": "co_cpu", "chapter": "数据通路", "type": "choice", "difficulty": "hard",
     "text": "单周期CPU效率低主因？", "options": ["时钟周期按最长指令", "无流水线", "指令集缺陷", "控制复杂"], "answer": 0, "source": "计组 第5章"},
    {"id": "q67", "subject": "os_process", "chapter": "信号量", "type": "choice", "difficulty": "hard",
     "text": "PV实现同步时信号量初值？", "options": ["0", "1", "n(资源数)", "-1"], "answer": 0, "source": "操作系统 第2章"},
    {"id": "q68", "subject": "ds_sort", "chapter": "快排", "type": "choice", "difficulty": "medium",
     "text": "快排每趟将哪个元素放最终位？", "options": ["最小值", "最大值", "枢轴元素", "中间值"], "answer": 2, "source": "数据结构 第8章"},
    {"id": "q69", "subject": "co_memory", "chapter": "Cache", "type": "choice", "difficulty": "medium",
     "text": "Cache映射方式中灵活性最高的是？", "options": ["直接映射", "全相联映射", "组相联映射", "混合映射"], "answer": 1, "source": "计组 第3章"},
    {"id": "q70", "subject": "os_process", "chapter": "PV操作", "type": "choice", "difficulty": "medium",
     "text": "生产者-消费者互斥P/V信号量初值？", "options": ["0", "1", "n", "-1"], "answer": 1, "source": "操作系统 第2章"},
    {"id": "q71", "subject": "ds_search", "chapter": "B+树", "type": "choice", "difficulty": "hard",
     "text": "B+树相比B树最大优势？", "options": ["查询更快", "范围查找高效", "插入更快", "删除更快"], "answer": 1, "source": "数据结构 第7章"},
    {"id": "q72", "subject": "co_data", "chapter": "IEEE754", "type": "choice", "difficulty": "hard",
     "text": "IEEE754单精度浮点偏置值？", "options": ["127", "128", "1023", "255"], "answer": 0, "source": "计组 第2章"},
    {"id": "q73", "subject": "security", "chapter": "数字签名", "type": "choice", "difficulty": "medium",
     "text": "数字签名使用的加密体制？", "options": ["对称", "非对称", "哈希", "混合"], "answer": 1, "source": "计网 第7章"},
    {"id": "q74", "subject": "os_memory", "chapter": "分页", "type": "choice", "difficulty": "easy",
     "text": "逻辑地址→物理地址转换由谁完成？", "options": ["CPU硬件(MMU)", "OS", "编译器", "链接器"], "answer": 0, "source": "操作系统 第3章"},
    {"id": "q75", "subject": "ds_graph", "chapter": "拓扑排序", "type": "choice", "difficulty": "medium",
     "text": "有向无环图拓扑排序可得到？", "options": ["唯一序列", "可能多个序列", "逆序", "零序列"], "answer": 1, "source": "数据结构 第6章"},
    {"id": "q76", "subject": "co_bus", "chapter": "总线", "type": "choice", "difficulty": "medium",
     "text": "支持多主设备的总线仲裁方式？", "options": ["链式查询", "计数器查询", "独立请求", "同步定时"], "answer": 2, "source": "计组 第6章"},
    {"id": "q77", "subject": "co_memory", "chapter": "主存", "type": "compute", "difficulty": "medium",
     "text": "CPU地址24根按字节寻址最大容量MB？", "answer": "16", "source": "计组 第3章"},
    {"id": "q78", "subject": "os_memory", "chapter": "页面置换", "type": "choice", "difficulty": "medium",
     "text": "FIFO置换算法可能产生什么异常？", "options": ["死锁", "Belady异常", "颠簸", "缺页异常"], "answer": 1, "source": "操作系统 第3章"},
    {"id": "q79", "subject": "datalink", "chapter": "VLAN", "type": "choice", "difficulty": "medium",
     "text": "802.1Q标签长度是？", "options": ["2B", "4B", "8B", "1B"], "answer": 1, "source": "计网 第3章"},
    {"id": "q80", "subject": "ds_search", "chapter": "哈希", "type": "compute", "difficulty": "medium",
     "text": "长度为12的有序表折半查找ASL(成功)？", "answer": "37/12≈3.08", "source": "数据结构 第7章"},
    {"id": "q81", "subject": "transport", "chapter": "TCP", "type": "fill", "difficulty": "medium",
     "text": "TCP首部最小长度______字节。", "answer": "20", "source": "计网 第5章"},
    {"id": "q82", "subject": "application", "chapter": "HTTP", "type": "choice", "difficulty": "easy",
     "text": "HTTP持久连接相对于非持久连接的优势？", "options": ["减少TCP握手", "更快响应", "并发请求", "更安全"], "answer": 0, "source": "计网 第6章"},
    {"id": "q83", "subject": "co_isa", "chapter": "RISC", "type": "choice", "difficulty": "medium",
     "text": "RISC特点不包括？", "options": ["指令数少", "寻址方式少", "微程序控制", "寄存器多"], "answer": 2, "source": "计组 第4章"},
    {"id": "q84", "subject": "ds_sort", "chapter": "基数排序", "type": "choice", "difficulty": "medium",
     "text": "基数排序的稳定性是？", "options": ["稳定", "不稳定", "取决于基数", "看趟数"], "answer": 0, "source": "数据结构 第8章"},
    {"id": "q85", "subject": "os_io", "chapter": "SPOOLing", "type": "choice", "difficulty": "medium",
     "text": "SPOOLing将独占设备变为？", "options": ["共享设备", "虚拟设备", "块设备", "字符设备"], "answer": 1, "source": "操作系统 第5章"},
    {"id": "q86", "subject": "network", "chapter": "路由协议", "type": "choice", "difficulty": "medium",
     "text": "OSPF基于什么算法？", "options": ["距离向量", "链路状态(Dijkstra)", "路径向量", "贪心"], "answer": 1, "source": "计网 第4章"},
    {"id": "q87", "subject": "ds_tree", "chapter": "哈夫曼", "type": "compute", "difficulty": "hard",
     "text": "七个叶子节点的哈夫曼树总节点数？", "answer": "13", "source": "数据结构 第5章"},
{"id": "q87", "subject": "ds_tree", "chapter": "哈夫曼", "type": "compute", "difficulty": "hard",
 "text": "七个叶子节点的哈夫曼树总节点数？", "answer": "13", "source": "数据结构 第5章"},
# ── 扩展题③（四科全覆盖，33题）──
{"id": "q88", "subject": "network", "chapter": "IP地址", "type": "choice", "difficulty": "easy",
 "text": "IPv6地址多少位？", "options": ["32", "64", "128", "256"], "answer": 2, "source": "计网 第4章"},
{"id": "q89", "subject": "ds_linear", "chapter": "链表", "type": "choice", "difficulty": "easy",
 "text": "单链表删除p的后继：", "options": ["p->next=p", "p->next=p->next->next", "p=p->next", "free(p)"], "answer": 1, "source": "数据结构 第2章"},
{"id": "q90", "subject": "ds_tree", "chapter": "AVL", "type": "choice", "difficulty": "hard",
 "text": "AVL插入引起LR旋转？", "options": ["左旋再右旋", "右旋再左旋", "单左旋", "单右旋"], "answer": 0, "source": "数据结构 第5章"},
{"id": "q91", "subject": "ds_graph", "chapter": "MST", "type": "choice", "difficulty": "medium",
 "text": "Kruskal适合什么图？", "options": ["稠密图", "稀疏图", "有向图", "带负权图"], "answer": 1, "source": "数据结构 第6章"},
{"id": "q92", "subject": "ds_sort", "chapter": "归并", "type": "fill", "difficulty": "medium",
 "text": "二路归并空间复杂度______。", "answer": "O(n)", "source": "数据结构 第8章"},
{"id": "q93", "subject": "co_overview", "chapter": "冯诺依曼", "type": "choice", "difficulty": "easy",
 "text": "冯诺依曼核心思想？", "options": ["存储程序", "并行", "分布式", "微程序"], "answer": 0, "source": "计组 第1章"},
{"id": "q94", "subject": "co_cpu", "chapter": "控制器", "type": "choice", "difficulty": "medium",
 "text": "微程序控制器核心？", "options": ["ALU", "控制存储器CM", "PC", "IR"], "answer": 1, "source": "计组 第5章"},
{"id": "q95", "subject": "co_memory", "chapter": "TLB", "type": "choice", "difficulty": "medium",
 "text": "TLB位于？", "options": ["硬盘", "CPU内MMU", "主存", "Cache"], "answer": 1, "source": "计组 第3章"},
{"id": "q96", "subject": "os_overview", "chapter": "OS特征", "type": "choice", "difficulty": "easy",
 "text": "OS最基本特征？", "options": ["并发与共享", "虚拟", "异步", "并行"], "answer": 0, "source": "操作系统 第1章"},
{"id": "q97", "subject": "os_process", "chapter": "调度", "type": "choice", "difficulty": "medium",
 "text": "中级调度功能？", "options": ["进程创建", "内存对换", "CPU分配", "资源回收"], "answer": 1, "source": "操作系统 第2章"},
{"id": "q98", "subject": "os_file", "chapter": "目录", "type": "choice", "difficulty": "easy",
 "text": "多级目录优点？", "options": ["减少命名冲突", "检索更快", "管理方便", "以上都是"], "answer": 3, "source": "操作系统 第4章"},
{"id": "q99", "subject": "os_process", "chapter": "PV", "type": "compute", "difficulty": "hard",
 "text": "S初值3，5次P、3次V后S=？", "answer": "1", "source": "操作系统 第2章"},
{"id": "q100", "subject": "transport", "chapter": "拥塞控制", "type": "choice", "difficulty": "medium",
 "text": "TCP拥塞避免窗口增长方式？", "options": ["线性", "指数", "对数", "固定"], "answer": 0, "source": "计网 第5章"},
{"id": "q101", "subject": "co_isa", "chapter": "指令", "type": "choice", "difficulty": "medium",
 "text": "RISC特点不包括？", "options": ["少指令", "少寻址", "微程序控制", "多寄存器"], "answer": 2, "source": "计组 第4章"},
{"id": "q102", "subject": "os_memory", "chapter": "页置换", "type": "choice", "difficulty": "medium",
 "text": "FIFO置换可能产生？", "options": ["死锁", "Belady异常", "颠簸", "缺页"], "answer": 1, "source": "操作系统 第3章"},
{"id": "q103", "subject": "ds_graph", "chapter": "MST", "type": "choice", "difficulty": "medium",
 "text": "Prim适合什么图？", "options": ["稠密图", "稀疏图", "有向图", "带负权图"], "answer": 0, "source": "数据结构 第6章"},
{"id": "q104", "subject": "co_memory", "chapter": "主存", "type": "compute", "difficulty": "medium",
 "text": "地址线24根，按字(32位)编址最大容量MB？", "answer": "64", "source": "计组 第3章"},
{"id": "q105", "subject": "os_io", "chapter": "DMA", "type": "choice", "difficulty": "medium",
 "text": "DMA传送以什么为单位？", "options": ["字", "字节", "数据块", "位"], "answer": 2, "source": "操作系统 第5章"},
{"id": "q106", "subject": "application", "chapter": "SMTP", "type": "fill", "difficulty": "easy",
 "text": "SMTP默认端口______。", "answer": "25", "source": "计网 第6章"},
{"id": "q107", "subject": "ds_tree", "chapter": "二叉树", "type": "compute", "difficulty": "hard",
 "text": "n个节点的完全二叉树深度？", "answer": "⌊log2n⌋+1", "source": "数据结构 第5章"},
{"id": "q108", "subject": "co_overview", "chapter": "性能", "type": "choice", "difficulty": "medium",
 "text": "CPI表示什么？", "options": ["每秒指令数", "每指令时钟周期", "每秒时钟", "程序总周期"], "answer": 1, "source": "计组 第1章"},
{"id": "q109", "subject": "os_process", "chapter": "线程", "type": "choice", "difficulty": "easy",
 "text": "用户级线程切换谁负责？", "options": ["OS内核", "用户态程序", "硬件", "MMU"], "answer": 1, "source": "操作系统 第2章"},
{"id": "q110", "subject": "ds_sort", "chapter": "堆排序", "type": "fill", "difficulty": "medium",
 "text": "建初始堆的时间复杂度______。", "answer": "O(n)", "source": "数据结构 第8章"},
{"id": "q111", "subject": "physical", "chapter": "奈氏准则", "type": "choice", "difficulty": "medium",
 "text": "奈氏准则给出什么上限？", "options": ["传输速率", "码元速率", "信噪比", "误码率"], "answer": 1, "source": "计网 第2章"},
{"id": "q112", "subject": "ds_queue", "chapter": "队列", "type": "choice", "difficulty": "easy",
 "text": "队列的应用不包括？", "options": ["层次遍历", "CPU调度", "函数调用", "缓冲区"], "answer": 2, "source": "数据结构 第3章"},
{"id": "q113", "subject": "co_data", "chapter": "补码", "type": "compute", "difficulty": "medium",
 "text": "8位补码10111011对应的十进制？", "answer": "-69", "source": "计组 第2章"},
{"id": "q114", "subject": "os_memory", "chapter": "分页", "type": "fill", "difficulty": "easy",
 "text": "分页系统中逻辑地址到物理地址转换由______完成。", "answer": "MMU(硬件)", "source": "操作系统 第3章"},
{"id": "q115", "subject": "datalink", "chapter": "CRC", "type": "fill", "difficulty": "medium",
 "text": "CRC中接收端余数为0说明______。", "answer": "无差错", "source": "计网 第3章"},
{"id": "q116", "subject": "security", "chapter": "数字签名", "type": "choice", "difficulty": "medium",
 "text": "数字签名提供哪种安全服务？", "options": ["机密性", "完整性+不可否认", "可用性", "认证"], "answer": 1, "source": "计网 第7章"},
{"id": "q117", "subject": "ds_string", "chapter": "KMP", "type": "fill", "difficulty": "hard",
 "text": "'ababa'的next数组(1开始)______。", "answer": "01123", "source": "数据结构 第4章"},
{"id": "q118", "subject": "co_io", "chapter": "中断", "type": "choice", "difficulty": "medium",
 "text": "中断响应优先级由什么决定？", "options": ["中断向量", "中断屏蔽字", "中断请求", "中断号"], "answer": 1, "source": "计组 第7章"},
{"id": "q119", "subject": "os_file", "chapter": "磁盘", "type": "choice", "difficulty": "medium",
 "text": "磁盘调度中电梯算法指的是？", "options": ["FCFS", "SSTF", "SCAN", "C-SCAN"], "answer": 2, "source": "操作系统 第4章"},
{"id": "q120", "subject": "network", "chapter": "子网划分", "type": "compute", "difficulty": "hard",
 "text": "192.168.1.0/26子网掩码？", "answer": "255.255.255.192", "source": "计网 第4章"},
{"id": "q121", "subject": "overview", "chapter": "分组交换", "type": "choice", "difficulty": "easy",
 "text": "分组交换比电路交换的优势？", "options": ["延迟低", "线路利用率高", "成本低", "带宽高"], "answer": 1, "source": "计网 第1章"},
{"id": "q122", "subject": "ds_tree", "chapter": "BST", "type": "fill", "difficulty": "medium",
 "text": "BST中序序列的性质是______。", "answer": "递增有序", "source": "数据结构 第5章"},
{"id": "q123", "subject": "co_data", "chapter": "ALU", "type": "choice", "difficulty": "medium",
 "text": "ALU核心组成是？", "options": ["累加器和暂存器", "加法器和控制逻辑", "寄存器和译码器", "计数器和比较器"], "answer": 1, "source": "计组 第2章"},
{"id": "q124", "subject": "os_process", "chapter": "进程", "type": "choice", "difficulty": "easy",
 "text": "进程控制块PCB的作用？", "options": ["代码存储", "描述进程状态和资源", "数据缓存", "指令执行"], "answer": 1, "source": "操作系统 第2章"},
{"id": "q125", "subject": "application", "chapter": "HTTP", "type": "choice", "difficulty": "medium",
 "text": "HTTP/2新增特性不包括？", "options": ["多路复用", "头部压缩", "服务端推送", "明文传输"], "answer": 3, "source": "计网 第6章"},
{"id": "q126", "subject": "ds_sort", "chapter": "外部排序", "type": "choice", "difficulty": "hard",
 "text": "外部排序主要时间开销在？", "options": ["CPU计算", "内存比较", "IO读写", "网络传输"], "answer": 2, "source": "数据结构 第8章"},
{"id": "q127", "subject": "co_memory", "chapter": "主存扩展", "type": "compute", "difficulty": "hard",
 "text": "用4片16K×8位芯片构成64K×8位存储器需多少位地址线？", "answer": "16", "source": "计组 第3章"},
{"id": "q128", "subject": "os_memory", "chapter": "虚拟内存", "type": "choice", "difficulty": "medium",
 "text": "缺页中断属于哪种中断？", "options": ["外中断", "内中断(异常)", "可屏蔽中断", "NMI"], "answer": 1, "source": "操作系统 第3章"},
]


SEED_SUBJECTS = {
    "overview": {"name": "计算机网络概述", "chapters": ["互联网与信息时代", "分组交换", "网络体系结构", "性能指标"]},
    "physical": {"name": "物理层", "chapters": ["传输媒体", "信道复用", "数字传输系统", "接入技术"]},
    "datalink": {"name": "数据链路层", "chapters": ["差错检测", "停止等待协议", "CSMA/CD", "以太网", "VLAN"]},
    "network": {"name": "网络层", "chapters": ["IP地址与编址", "ARP", "路由选择", "RIP/OSPF/BGP", "NAT", "IPv6"]},
    "transport": {"name": "运输层", "chapters": ["UDP", "TCP报文段", "可靠传输", "流量控制", "拥塞控制", "连接管理"]},
    "application": {"name": "应用层", "chapters": ["DNS", "WWW", "电子邮件", "FTP", "DHCP"]},
    "security": {"name": "网络安全", "chapters": ["机密性与密码学", "报文摘要", "数字签名", "SSL/TLS", "防火墙"]},
}

# ============================================================
# 计算机组成原理种子数据（408 统考）
# 9章：系统概述、数据表示、存储系统、指令系统、CPU、总线、I/O系统
# ============================================================

CO_SEED_KNOWLEDGE_CHUNKS = [
    # ---- 第1章 计算机系统概述 ----
    {"content": "计算机系统由硬件和软件两部分组成。硬件是物理实体，软件是程序和数据。计算机体系结构是程序员可见的属性（指令集、数据类型、寻址方式），计算机组成是实现体系结构的具体部件。", "metadata": {"subject": "co_overview", "chapter": "系统概述", "type": "knowledge_point"}},
    {"content": " Flynn分类法：SISD（单指令流单数据流）、SIMD（单指令流多数据流）、MISD（多指令流单数据流）、MIMD（多指令流多数据流）。现代多核CPU属于MIMD。", "metadata": {"subject": "co_overview", "chapter": "体系结构", "type": "knowledge_point"}},
    {"content": " 计算机性能指标：主频（时钟周期）、CPI（每指令周期数）、CPU时间=指令数×CPI×时钟周期时间、MIPS=指令数/(CPU时间×10^6)、MFLOPS=浮点操作数/(CPU时间×10^6)。", "metadata": {"subject": "co_overview", "chapter": "性能评价", "type": "knowledge_point"}},
    # ---- 第2章 数据的表示和运算 ----
    {"content": " 定点数表示：原码、反码、补码、移码。补码求法：正数同原码，负数除符号位外按位取反末位加1。移码常用于阶码，补码常用于数值计算。", "metadata": {"subject": "co_data", "chapter": "定点数", "type": "knowledge_point"}},
    {"content": " IEEE 754浮点数：单精度(32位)符号位1位，阶码8位(偏移127)，尾数23位；双精度(64位)符号位1位，阶码11位(偏移1023)，尾数52位。规格化数尾数最高位为1(隐含)。", "metadata": {"subject": "co_data", "chapter": "浮点数", "type": "knowledge_point"}},
    {"content": " 浮点数加减法步骤：对阶（小阶向大阶看齐）、尾数加减、规格化、舍入、溢出判断。溢出判断：阶码全1为无穷大/NaN，阶码全0为非规格化数。", "metadata": {"subject": "co_data", "chapter": "浮点运算", "type": "knowledge_point"}},
    # ---- 第3章 存储系统 ----
    {"content": " 存储层次结构：寄存器→Cache→主存→外存。速度递减，容量递增，成本递减。局部性原理：时间局部性（近期访问的指令/数据可能再次访问）、空间局部性（相邻存储单元可能被访问）。", "metadata": {"subject": "co_memory", "chapter": "存储层次", "type": "knowledge_point"}},
    {"content": " SRAM（静态RAM）：双稳态触发器存储，速度快，集成度低，功耗高，用作Cache。DRAM（动态RAM）：电容存储，速度慢，集成度高，功耗低，需刷新，用作主存。", "metadata": {"subject": "co_memory", "chapter": "半导体存储", "type": "knowledge_point"}},
    {"content": " Cache地址映射：直接映射（主存块i→Cache块i mod 2^c）、全相联映射（主存块可放Cache任意位置）、组相联映射（主存块i→Cache组i mod 组数，组内全相联）。", "metadata": {"subject": "co_memory", "chapter": "Cache映射", "type": "knowledge_point"}},
    {"content": " 虚拟内存实现：页式（固定大小页）、段式（可变长度段）、段页式。页表机制：每个进程有页表，页表项包含页框号、有效位、访问位、修改位。TLB（快表）加速地址变换。", "metadata": {"subject": "co_memory", "chapter": "虚拟内存", "type": "knowledge_point"}},
    # ---- 第4章 指令系统 ----
    {"content": " 指令格式：操作码+地址码。操作码长度固定则编码简单但指令数少；操作码长度可变（扩展操作码）则指令数多。地址码长度：零地址、一地址、二地址、三地址。", "metadata": {"subject": "co_isa", "chapter": "指令格式", "type": "knowledge_point"}},
    {"content": " 寻址方式：立即寻址（快，但地址空间受限）、直接寻址（简单，但需访问内存）、间接寻址（灵活，但速度慢）、寄存器寻址（快）、寄存器间接寻址、基址寻址、变址寻址、相对寻址、堆栈寻址。", "metadata": {"subject": "co_isa", "chapter": "寻址方式", "type": "knowledge_point"}},
    {"content": " CISC（复杂指令集）：指令丰富，长度可变，寻址方式多，如x86。RISC（精简指令集）：指令少且长度固定，寻址方式少，硬连线控制，如ARM、MIPS。", "metadata": {"subject": "co_isa", "chapter": "CISC/RISC", "type": "knowledge_point"}},
    # ---- 第5章 中央处理器 ----
    {"content": " CPU功能：取指令、分析指令、执行指令。数据通路：ALU、寄存器、数据总线。硬连线控制器：速度快，设计复杂。微程序控制器：灵活性高，速度慢。", "metadata": {"subject": "co_cpu", "chapter": "CPU功能", "type": "knowledge_point"}},
    {"content": " 指令流水线：将指令执行分为取指、译码、执行、访存、写回五段。理想情况下CPI=1。相关：数据相关（RAW）、控制相关（分支指令）、结构相关（资源冲突）。", "metadata": {"subject": "co_cpu", "chapter": "流水线", "type": "knowledge_point"}},
    {"content": " 流水线性能：加速比=流水线深度/(1+冒险 stalls)；吞吐率=1/最长段周期。解决冒险：数据前递（转发）、指令调度（延迟槽）、分支预测（静态/动态）。", "metadata": {"subject": "co_cpu", "chapter": "流水线性能", "type": "knowledge_point"}},
    # ---- 第6章 总线 ----
    {"content": " 总线分类：数据总线（DB，双向，位数=字长）、地址总线（AB，单向，位数=寻址空间）、控制总线（CB，传输控制信号）。总线仲裁：集中式（链式、计数器定时、独立请求）、分布式（逻辑环、冲突检测）。", "metadata": {"subject": "co_bus", "chapter": "总线分类", "type": "knowledge_point"}},
    {"content": " 总线操作：总线传输周期：申请分配、寻址、传数、结束。同步通信（统一时钟）、异步通信（应答式）。总线带宽=数据线宽度×总线频率。", "metadata": {"subject": "co_bus", "chapter": "总线操作", "type": "knowledge_point"}},
    # ---- 第7章 I/O系统 ----
    {"content": " I/O方式：程序查询（CPU忙等，效率低）、程序中断（CPU可并行，需保存现场）、DMA（外设直接访存，适合大批量传输）、通道方式（复杂I/O管理）。", "metadata": {"subject": "co_io", "chapter": "I/O方式", "type": "knowledge_point"}},
    {"content": " 中断处理过程：关中断→保存断点和现场→识别中断源→中断服务→开中断→返回。中断屏蔽字：设置优先级，高优先级中断可打断低优先级。中断向量表：存放各中断服务程序入口地址。", "metadata": {"subject": "co_io", "chapter": "中断", "type": "knowledge_point"}},
]

# ============================================================
# 操作系统种子数据（408 统考）
# 9章：概述、进程、调度、同步、死锁、内存、文件系统、I/O
# ============================================================

OS_SEED_KNOWLEDGE_CHUNKS = [
    # ---- 第1章 操作系统概述 ----
    {"content": " 操作系统功能：进程管理、内存管理、文件管理、设备管理、作业管理。OS是用户与计算机硬件之间的接口，提供运行环境。", "metadata": {"subject": "os_overview", "chapter": "OS概述", "type": "knowledge_point"}},
    {"content": " 系统调用：应用程序请求OS服务的唯一接口。常见系统调用：进程控制(create/exit/wait)、文件操作(open/read/write/close)、设备操作、信息维护、通信。", "metadata": {"subject": "os_overview", "chapter": "系统调用", "type": "knowledge_point"}},
    # ---- 第2章 进程管理 ----
    {"content": " 进程是程序的一次执行，是系统进行资源分配和调度的一个独立单位。进程状态：运行、就绪、阻塞。进程控制块(PCB)：进程存在的唯一标识，包含进程状态、程序计数器、CPU寄存器、调度信息等。", "metadata": {"subject": "os_process", "chapter": "进程与线程", "type": "knowledge_point"}},
    {"content": " 线程是进程内的一个执行单元，是CPU调度的基本单位。线程优点：减少并发执行时空切换开销、提高系统效率、通信方便。线程状态：运行、就绪、阻塞。", "metadata": {"subject": "os_process", "chapter": "进程与线程", "type": "knowledge_point"}},
    {"content": " 进程控制：进程创建（fork）、进程终止（exit）、进程阻塞（wait）、进程唤醒（wakeup）。原语操作：不可中断的过程。", "metadata": {"subject": "os_process", "chapter": "进程控制", "type": "knowledge_point"}},
    # ---- 第3章 处理机调度 ----
    {"content": " 调度层次：作业调度（高级调度，进入外存→内存）、内存调度（中级调度，挂起→就绪）、进程调度（低级调度，就绪→运行）。调度方式：抢占式（可剥夺）、非抢占式（不可剥夺）。", "metadata": {"subject": "os_sched", "chapter": "调度层次", "type": "knowledge_point"}},
    {"content": " 调度算法：FCFS（先来先服务，非抢占，平均等待时间长）、SJF（最短作业优先，最优平均等待时间，但可能饥饿）、优先级调度（静态/动态，可能导致饥饿）、RR（时间片轮转，抢占式，响应时间好）、多级队列（分优先级队列）、多级反馈队列（进程可升级/降级）。", "metadata": {"subject": "os_sched", "chapter": "调度算法", "type": "knowledge_point"}},
    # ---- 第4章 同步与互斥 ----
    {"content": " 临界资源：一次只允许一个进程访问的资源。临界区：进程中访问临界资源的程序段。同步：进程间直接制约关系；互斥：进程间间接制约关系（竞争临界资源）。", "metadata": {"subject": "os_sync", "chapter": "同步互斥", "type": "knowledge_point"}},
    {"content": " 信号量机制：整型信号量S>0表示可用资源数，S<=0表示等待进程数。P操作（wait）：S=S-1，若S<0则阻塞；V操作（signal）：S=S+1，若S<=0则唤醒。", "metadata": {"subject": "os_sync", "chapter": "信号量", "type": "knowledge_point"}},
    {"content": " 经典同步问题：生产者-消费者（互斥+同步）、读者-写者（读写互斥、写写互斥、读读共享）、哲学家进餐（防止死锁）、 Sleeping Barber（理发师问题）。", "metadata": {"subject": "os_sync", "chapter": "经典问题", "type": "knowledge_point"}},
    # ---- 第5章 死锁 ----
    {"content": " 死锁四个必要条件：互斥条件、请求和保持条件、不剥夺条件、环路等待条件。只要破坏一个条件即可防止死锁。", "metadata": {"subject": "os_deadlock", "chapter": "死锁条件", "type": "knowledge_point"}},
    {"content": " 死锁预防：破坏互斥（Spooling技术）、破坏请求和保持（一次性请求所有资源）、破坏不剥夺（资源可剥夺）、破坏环路等待（资源有序分配）。死锁避免：银行家算法（安全性算法、资源请求算法）。", "metadata": {"subject": "os_deadlock", "chapter": "死锁处理", "type": "knowledge_point"}},
    {"content": " 死锁检测与解除：资源分配图简化法检测死锁。解除方法：资源剥夺法、撤销进程法（终止进程并剥夺资源）。", "metadata": {"subject": "os_deadlock", "chapter": "死锁检测", "type": "knowledge_point"}},
    # ---- 第6章 内存管理 ----
    {"content": " 内存分配方式：连续分配（单一连续、固定分区、可变分区）、非连续分配（分页、分段、段页式）。连续分配特点：内存利用率低，存在外部碎片。", "metadata": {"subject": "os_mem", "chapter": "内存分配", "type": "knowledge_point"}},
    {"content": " 分页存储管理：将物理内存分成固定大小的帧，逻辑空间分成同样大小的页。页表实现地址映射：逻辑地址→页号+页内偏移→查页表得帧号→物理地址。快表（TLB）加速页表访问。", "metadata": {"subject": "os_mem", "chapter": "分页管理", "type": "knowledge_point"}},
    {"content": " 分段存储管理：按程序逻辑段划分（代码段、数据段、堆栈段），每段长度可变。段表：段号、段长、段基址。优点：便于共享和保护，便于动态链接。", "metadata": {"subject": "os_mem", "chapter": "分段管理", "type": "knowledge_point"}},
    # ---- 第7章 虚拟内存 ----
    {"content": " 虚拟内存：基于局部性原理，只装入部分页面到内存。请求分页：缺页中断→查找空闲帧→读入页面→修改页表→重新执行。页面置换算法：OPT（最优，不可实现）、FIFO（可能Belady异常）、LRU（最近最少使用）、Clock（近似LRU）。", "metadata": {"subject": "os_vmem", "chapter": "虚拟内存", "type": "knowledge_point"}},
    {"content": " 页面分配策略：固定分配（每个进程固定页框数）、可变分配（进程运行期间可调整）。置换策略：全局置换（从所有进程选）、局部置换（从本进程选）。工作集模型：进程在一段时间内访问的页面集合。", "metadata": {"subject": "os_vmem", "chapter": "页面置换", "type": "knowledge_point"}},
    # ---- 第8章 文件系统 ----
    {"content": " 文件逻辑结构：流式文件（无结构，字节序列）、记录式文件（有结构，定长/变长记录）。文件物理结构：连续分配、链接分配（隐式/显式）、索引分配（单级/多级/混合）。", "metadata": {"subject": "os_file", "chapter": "文件结构", "type": "knowledge_point"}},
    {"content": " 目录结构：单级目录（简单但命名冲突）、两级目录（树形，用户独立）、树形目录（多级，路径唯一）、图形目录（可共享，复杂）。文件共享：硬链接（同一索引节点，共享文件）、符号链接（新文件指向原文件路径）。", "metadata": {"subject": "os_file", "chapter": "目录与共享", "type": "knowledge_point"}},
    {"content": " 磁盘调度算法：FCFS（先来先服务，公平但效率低）、SSTF（最短寻道时间优先，效率高但可能饥饿）、SCAN（电梯算法，来回扫描）、C-SCAN（循环扫描，均匀响应）、LOOK（只在有请求处停下）。", "metadata": {"subject": "os_file", "chapter": "磁盘调度", "type": "knowledge_point"}},
    # ---- 第9章 I/O管理 ----
    {"content": " I/O控制方式：程序查询（CPU忙等）、中断驱动（CPU与I/O并行）、DMA（外设直接访存，适合高速外设）、通道控制（复杂I/O管理）。设备分类：块设备（磁盘）、字符设备（键盘/显示器）、网络设备。", "metadata": {"subject": "os_io", "chapter": "I/O方式", "type": "knowledge_point"}},
    {"content": " 缓冲区管理：单缓冲（效率低）、双缓冲（解决生产者-消费者问题）、循环缓冲（多缓冲，适合高速外设）。SPOOLing技术：用磁盘模拟设备，实现虚拟设备，将独占设备改造为共享设备。", "metadata": {"subject": "os_io", "chapter": "缓冲技术", "type": "knowledge_point"}},
]


KNOWLEDGE_GRAPH = {
    "nodes": [
        # 数据结构（group 1-4）
        {"id": "ds_linear", "label": "线性表", "group": 1},
        {"id": "ds_stack", "label": "栈和队列", "group": 1},
        {"id": "ds_string", "label": "串", "group": 2},
        {"id": "ds_tree", "label": "树和二叉树", "group": 2},
        {"id": "ds_graph", "label": "图", "group": 3},
        {"id": "ds_search", "label": "查找", "group": 3},
        {"id": "ds_sort", "label": "排序", "group": 4},
        # 计算机组成原理（group 5-7）
        {"id": "co_overview", "label": "计算机系统概述", "group": 5},
        {"id": "co_data", "label": "数据表示和运算", "group": 5},
        {"id": "co_memory", "label": "存储系统", "group": 6},
        {"id": "co_cpu", "label": "中央处理器", "group": 6},
        {"id": "co_bus", "label": "总线", "group": 7},
        {"id": "co_io", "label": "I/O系统", "group": 7},
        # 操作系统（group 8-10）
        {"id": "os_overview", "label": "操作系统概述", "group": 8},
        {"id": "os_process", "label": "进程管理", "group": 8},
        {"id": "os_sched", "label": "处理机调度", "group": 9},
        {"id": "os_sync", "label": "同步与互斥", "group": 9},
        {"id": "os_deadlock", "label": "死锁", "group": 10},
        {"id": "os_mem", "label": "内存管理", "group": 10},
        {"id": "os_vmem", "label": "虚拟内存", "group": 11},
        {"id": "os_file", "label": "文件系统", "group": 11},
        {"id": "os_io", "label": "I/O管理", "group": 12},
        # 计算机网络（group 13-19）
        {"id": "overview", "label": "计算机网络概述", "group": 13},
        {"id": "architecture", "label": "体系结构", "group": 13},
        {"id": "switching", "label": "分组交换", "group": 13},
        {"id": "physical", "label": "物理层", "group": 14},
        {"id": "media", "label": "传输媒体", "group": 14},
        {"id": "multiplex", "label": "信道复用", "group": 14},
        {"id": "datalink", "label": "数据链路层", "group": 15},
        {"id": "csma", "label": "CSMA/CD", "group": 15},
        {"id": "ethernet", "label": "以太网", "group": 15},
        {"id": "vlan", "label": "VLAN", "group": 15},
        {"id": "network", "label": "网络层", "group": 16},
        {"id": "ip", "label": "IP协议", "group": 16},
        {"id": "arp", "label": "ARP", "group": 16},
        {"id": "routing", "label": "路由选择", "group": 16},
        {"id": "transport", "label": "运输层", "group": 17},
        {"id": "tcp", "label": "TCP协议", "group": 17},
        {"id": "udp", "label": "UDP协议", "group": 17},
        {"id": "app", "label": "应用层", "group": 18},
        {"id": "dns", "label": "DNS", "group": 18},
        {"id": "http", "label": "HTTP", "group": 18},
        {"id": "security", "label": "网络安全", "group": 19},
        {"id": "tls", "label": "SSL/TLS", "group": 19},
        {"id": "firewall", "label": "防火墙", "group": 19},
    ],
    "edges": [
        # 数据结构内部关系
        {"source": "ds_linear", "target": "ds_stack"},
        {"source": "ds_linear", "target": "ds_string"},
        {"source": "ds_linear", "target": "ds_tree"},
        {"source": "ds_tree", "target": "ds_graph"},
        {"source": "ds_linear", "target": "ds_search"},
        {"source": "ds_linear", "target": "ds_sort"},
        # 计算机组成原理内部关系
        {"source": "co_overview", "target": "co_data"},
        {"source": "co_overview", "target": "co_memory"},
        {"source": "co_data", "target": "co_memory"},
        {"source": "co_memory", "target": "co_cpu"},
        {"source": "co_cpu", "target": "co_bus"},
        {"source": "co_bus", "target": "co_io"},
        # 操作系统内部关系
        {"source": "os_overview", "target": "os_process"},
        {"source": "os_process", "target": "os_sched"},
        {"source": "os_process", "target": "os_sync"},
        {"source": "os_sync", "target": "os_deadlock"},
        {"source": "os_overview", "target": "os_mem"},
        {"source": "os_mem", "target": "os_vmem"},
        {"source": "os_overview", "target": "os_file"},
        {"source": "os_overview", "target": "os_io"},
        # 计算机网络内部关系
        {"source": "overview", "target": "architecture"},
        {"source": "overview", "target": "switching"},
        {"source": "overview", "target": "physical"},
        {"source": "physical", "target": "media"},
        {"source": "physical", "target": "multiplex"},
        {"source": "physical", "target": "datalink"},
        {"source": "datalink", "target": "csma"},
        {"source": "datalink", "target": "ethernet"},
        {"source": "datalink", "target": "vlan"},
        {"source": "datalink", "target": "network"},
        {"source": "network", "target": "ip"},
        {"source": "network", "target": "arp"},
        {"source": "network", "target": "routing"},
        {"source": "network", "target": "transport"},
        {"source": "transport", "target": "tcp"},
        {"source": "transport", "target": "udp"},
        {"source": "transport", "target": "app"},
        {"source": "app", "target": "dns"},
        {"source": "app", "target": "http"},
        {"source": "app", "target": "security"},
        {"source": "security", "target": "tls"},
        {"source": "security", "target": "firewall"},
        # 跨课程依赖关系（408学习路径）
        {"source": "ds_linear", "target": "co_overview"},
        {"source": "co_memory", "target": "os_mem"},
        {"source": "os_process", "target": "network"},
    ],
}

LEARNING_PATH_DAG = {
    # === 408 统考四门课 ===
    # 数据结构（第1-8章）
    "数据结构": {
        "id": "ds", "chapter": 1, "prerequisites": [],
        "topics": ["线性表", "栈和队列", "串", "数组和广义表", "树和二叉树", "图", "查找", "排序"],
    },
    # 计算机组成原理（第1-9章）
    "计算机组成原理": {
        "id": "co", "chapter": 2, "prerequisites": ["数据结构"],
        "topics": ["计算机系统概述", "数据的表示和运算", "存储系统", "指令系统", "中央处理器", "总线", "I/O系统"],
    },
    # 操作系统（第1-9章）
    "操作系统": {
        "id": "os", "chapter": 3, "prerequisites": ["计算机组成原理"],
        "topics": ["操作系统概述", "进程管理", "处理机调度", "同步与互斥", "死锁", "内存管理", "虚拟内存", "文件系统", "I/O管理"],
    },
    # 计算机网络（第1-7章）
    "计算机网络": {
        "id": "cn", "chapter": 4, "prerequisites": ["操作系统"],
        "topics": ["计算机网络体系结构", "物理层", "数据链路层", "网络层", "运输层", "应用层", "网络安全"],
    },
}

